In [32]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv("../data/processed/energy_clean.csv")

df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Timestamp
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0,16/12/2006 17:24:00
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,16/12/2006 17:25:00
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,16/12/2006 17:26:00
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,16/12/2006 17:27:00
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0,16/12/2006 17:28:00

In [34]:
print(df.columns.tolist())

['Date', 'Time', 'Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3', 'Timestamp']

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 10 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   str
 1   Time                   str
 2   Global_active_power    float64
 3   Global_reactive_power  float64
 4   Voltage                float64
 5   Global_intensity       float64
 6   Sub_metering_1         float64
 7   Sub_metering_2         float64
 8   Sub_metering_3         float64
 9   Timestamp              str
dtypes: float64(7), str(3)
memory usage: 229.5 MB

In [36]:
df["Datetime"] = pd.to_datetime(
    df["Date"] + " " + df["Time"]
)

C:\Users\User\AppData\Local\Temp\ipykernel_57340\777532755.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Datetime"] = pd.to_datetime(

In [37]:
df["Datetime"] = pd.to_datetime(df["Timestamp"])

C:\Users\User\AppData\Local\Temp\ipykernel_57340\1411980032.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Datetime"] = pd.to_datetime(df["Timestamp"])

In [38]:
df["Hour"] = df["Datetime"].dt.hour

df["Day"] = df["Datetime"].dt.day

df["Month"] = df["Datetime"].dt.month

df["DayOfWeek"] = df["Datetime"].dt.dayofweek

df["Week"] = df["Datetime"].dt.isocalendar().week

df["Quarter"] = df["Datetime"].dt.quarter

In [39]:
df["Weekend"] = (
    df["DayOfWeek"].isin([5, 6])
).astype(int)

In [40]:
print(df.columns.tolist())

['Date', 'Time', 'Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3', 'Timestamp', 'Datetime', 'Hour', 'Day', 'Month', 'DayOfWeek', 'Week', 'Quarter', 'Weekend']

In [41]:
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Timestamp,Datetime,Hour,Day,Month,DayOfWeek,Week,Quarter,Weekend
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0,16/12/2006 17:24:00,2006-12-16 17:24:00,17,16,12,5,50,4,1
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,16/12/2006 17:25:00,2006-12-16 17:25:00,17,16,12,5,50,4,1
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,16/12/2006 17:26:00,2006-12-16 17:26:00,17,16,12,5,50,4,1
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,16/12/2006 17:27:00,2006-12-16 17:27:00,17,16,12,5,50,4,1
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0,16/12/2006 17:28:00,2006-12-16 17:28:00,17,16,12,5,50,4,1

In [42]:
df["Hour"] = df["Datetime"].dt.hour

df["Day"] = df["Datetime"].dt.day

df["Month"] = df["Datetime"].dt.month

df["DayOfWeek"] = df["Datetime"].dt.dayofweek

df["Week"] = df["Datetime"].dt.isocalendar().week

df["Quarter"] = df["Datetime"].dt.quarter

df["Weekend"] = df["DayOfWeek"].isin([5, 6]).astype(int)

In [43]:
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Timestamp,Datetime,Hour,Day,Month,DayOfWeek,Week,Quarter,Weekend
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0,16/12/2006 17:24:00,2006-12-16 17:24:00,17,16,12,5,50,4,1
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,16/12/2006 17:25:00,2006-12-16 17:25:00,17,16,12,5,50,4,1
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,16/12/2006 17:26:00,2006-12-16 17:26:00,17,16,12,5,50,4,1
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,16/12/2006 17:27:00,2006-12-16 17:27:00,17,16,12,5,50,4,1
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0,16/12/2006 17:28:00,2006-12-16 17:28:00,17,16,12,5,50,4,1

In [44]:
df["Lag_1"] = df["Global_active_power"].shift(1)

In [45]:
df["Lag_24"] = df["Global_active_power"].shift(24)

In [46]:
df["Lag_168"] = df["Global_active_power"].shift(168)

In [47]:
df["RollingMean_24"] = (
    df["Global_active_power"]
    .rolling(window=24)
    .mean()
)

df["RollingStd_24"] = (
    df["Global_active_power"]
    .rolling(window=24)
    .std()
)

In [48]:
df["Difference"] = df["Global_active_power"].diff()

df["PctChange"] = df["Global_active_power"].pct_change()

In [49]:
threshold = df["Global_active_power"].quantile(0.75)

df["Peak"] = (
    df["Global_active_power"] > threshold
).astype(int)

In [50]:
df.isnull().sum()

Date                         0
Time                         0
Global_active_power      25903
Global_reactive_power    25903
Voltage                  25903
Global_intensity         25903
Sub_metering_1           25903
Sub_metering_2           25903
Sub_metering_3           25903
Timestamp                    0
Datetime                     0
Hour                         0
Day                          0
Month                        0
DayOfWeek                    0
Week                         0
Quarter                      0
Weekend                      0
Lag_1                    25904
Lag_24                   25927
Lag_168                  26071
RollingMean_24           26280
RollingStd_24            26280
Difference               25920
PctChange                25920
Peak                         0
dtype: int64

In [51]:
df = df.dropna()

In [52]:
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Timestamp,...,Quarter,Weekend,Lag_1,Lag_24,Lag_168,RollingMean_24,RollingStd_24,Difference,PctChange,Peak
168,16/12/2006,20:12:00,3.400,0.140,233.62,14.4,0.0,0.0,17.0,16/12/2006 20:12:00,...,4,1,3.410,3.380,4.216,3.286333,0.083777,-0.010,-0.002933,1
169,16/12/2006,20:13:00,3.400,0.140,233.64,14.4,0.0,0.0,17.0,16/12/2006 20:13:00,...,4,1,3.400,3.404,5.360,3.286167,0.083537,0.000,0.000000,1
170,16/12/2006,20:14:00,3.388,0.140,233.26,14.4,0.0,0.0,16.0,16/12/2006 20:14:00,...,4,1,3.400,3.378,5.374,3.286583,0.084038,-0.012,-0.003529,1
171,16/12/2006,20:15:00,3.370,0.086,233.90,14.4,0.0,0.0,17.0,16/12/2006 20:15:00,...,4,1,3.388,3.388,5.388,3.285833,0.083170,-0.018,-0.005313,1
172,16/12/2006,20:16:00,3.332,0.000,233.68,14.2,0.0,0.0,17.0,16/12/2006 20:16:00,...,4,1,3.370,3.376,3.666,3.284000,0.081565,-0.038,-0.011276,1

In [53]:
df.shape

(2047446, 26)

In [54]:
import os

os.makedirs("../data/processed", exist_ok=True)

df.to_csv(
    "../data/processed/feature_engineered_dataset.csv",
    index=False
)

print("Dataset Saved Successfully!")

Dataset Saved Successfully!

In [55]:
df.columns.tolist()

['Date',
 'Time',
 'Global_active_power',
 'Global_reactive_power',
 'Voltage',
 'Global_intensity',
 'Sub_metering_1',
 'Sub_metering_2',
 'Sub_metering_3',
 'Timestamp',
 'Datetime',
 'Hour',
 'Day',
 'Month',
 'DayOfWeek',
 'Week',
 'Quarter',
 'Weekend',
 'Lag_1',
 'Lag_24',
 'Lag_168',
 'RollingMean_24',
 'RollingStd_24',
 'Difference',
 'PctChange',
 'Peak']